name: CD

on:
  workflow_run:
    workflows: ["CI"] # Name of your CI workflow
    types:
      - completed # Trigger only when the CI workflow completes
    branches:
      - main # Or the branch your CI runs on
jobs:
    release-tag:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: checkout code
          uses: actions/checkout@v5
          with:
            fetch-depth: 0
        - name: Get latest tag
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          run: |
            echo "tag=$(cat changelog.md | sed -n 's/.*\[\(v[0-9.]*\)\].*/\1/p'|  head -n 1 )" >> $GITHUB_ENV
        - name: release tag
          run: |    
            echo $tag
            # configuring git
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            echo ${{github.event.workflow_run.head_commit.message}}
            git tag -a $tag -m "${{github.event.workflow_run.head_commit.message}}"
            git push origin --tag
        - name: create a release
          run: |
           env GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bootstrap main.go
           zip bootstrap.zip bootstrap
           notes=$(awk -v ver=$tag '/^## \[v[0-9]+\.[0-9]+\.[0-9]+\]/ {flag=($0 ~ "## \\[" ver "\\]"); next} flag' changelog.md)
           gh release create $tag bootstrap.zip --title "${{github.event.workflow_run.head_commit.message}}" --notes "${notes}"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}