name: CD

on:
  workflow_run:
    workflows: ["CI"] # Name of your CI workflow
    types:
      - completed # Trigger only when the CI workflow completes
    branches:
      - main # Or the branch your CI runs on
jobs:
    release-tag:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: checkout code
          uses: actions/checkout@v5
          with:
            fetch-depth: 0
        - name: Create tag
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          run: |
            tag=$(cat changelog.md | sed -n 's/.*\[\(v[0-9.]*\)\].*/\1/p'|  head -n 1 )
            echo $tag
            echo ${{github.event.workflow_run.head_commit.message}}
            # git tag -a $tag -m "${{github.event.workflow_run.head_commit.message}}"