name: CD

on:
  workflow_run:
    workflows: ["CI"] # Name of your CI workflow
    types:
      - completed # Trigger only when the CI workflow completes
    branches:
      - main # Or the branch your CI runs on
jobs:
    release-tag:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        steps:
        - name: Create Release
          uses: rymndhng/release-on-push-action@master
          with:
            bump_version_scheme: minor